### ISSUE TITLE
Support `raise HTTPFound`

### ISSUE THREAD

**Issue by u8sand** [playpauseandstop/rororo#191]
I can't seem to get redirects working when using rororo, the rororo exception handler seems to break it even when `use_error_middleware=False`.

Nonetheless, thanks for creating this -- I love openapi first and have recently starting using aiohttp for most things.

**Comment by playpauseandstop** [comment]
Hi @u8sand 

Thanks for reporting this.

Couple of past months I don't have enough time to share between my work and this project, but in Sep I'll have some spare time to work on `rororo` issues.

This issue seems reasonable, I'll update `rororo` test suite (and examples applications) to ensure raising `web.HttpFound` supported properly.

**Comment by q0w** [comment]
@playpauseandstop
It works, if u pass `error_middleware_kwargs={"ignore_exceptions": web.HTTPFound}` to `setup_openapi`
