### ISSUE TITLE
Enhancements to aiohttp.web

### ISSUE THREAD

**Issue by playpauseandstop** [playpauseandstop/rororo#5]
There are several desired enhancements to `aiohttp.web` library that widely used in backend applications which should be added to `rororo`,

* Improved `Application` to support debug mode and proper logging while serving with gunicorn
* `add_route` context manager
* Handling single static files, not directories
* Error handling middleware

**Comment by playpauseandstop** [comment]
`add_route` context manager example,

```python
from rororo.aio.routes import add_route_context

from . import api as api_views


app = Application(...)

with add_route_context(app, api_views, '/api', 'api') as add_route:
    add_route('GET', '/', 'index')
    add_route('POST', '/posts', 'add_post')
    add_route('GET', '/posts', 'list_posts')
```

This should creates 3 route handlers,

```
GET /api/ -> api.index
POST /api/posts -> api.add_post
GET /api/posts -> api.list_posts
```

**Comment by playpauseandstop** [comment]
`add_static` context manager example,

```python
from pathlib import Path

rel = Path(__file__).dirname

app = Application(...)

static_dir = str((rel / '..' / 'static').absolute())
with add_static_context(app, static_dir) as add_static:
    add_static('/favicon.ico', 'images/favicon.ico')
    add_static('/static')
```

This should create 2 static route handlers,

```
GET /favicon.ico -> /static/images/favicon.ico
GET /static/{filename} -> /static/{filename}
```

**Comment by sloria** [comment]
Greetings! 

I hope you don't mind, but I adapted your `add_route_context` helper in a utilities package I just published: [aiohttp_utils](https://github.com/sloria/aiohttp_utils). 

I made a few changes to make the following possible:

1. Passing handlers rather than strings to `add_route`
2. Passing both module names and handler names as strings.

See the examples here: https://aiohttp-utils.readthedocs.org/en/latest/modules/routing.html#aiohttp_utils.routing.add_route_context

I'd be glad to contribute them to rororo if you'd like.

**Comment by playpauseandstop** [comment]
@sloria 

Greetings! Great to hear about `aiohttp_utils`, closing this ticket in favor of,

* Using `add_route_context` from [aiohttp_utils](https://github.com/sloria/aiohttp_utils)
* `add_static_context` is deprecated cause of planned improvements to static handling in `aiohttp`, https://github.com/KeepSafe/aiohttp/issues/468#issuecomment-148781109
* Error handling middleware and other middlewares are subject to rethink
